### ISSUE TITLE
Just my ideas

### ISSUE THREAD

**Issue by evrial** [SmilyOrg/photofield#100]
I wish the Readme explicitly stated that all photos without Exif are ignored, I have most of my library like that so photofield is almost useless.
Also I know this is out of project scope but Automatic Mobile Upload is the missing piece to make this shiny and competitive. If you push the limits in that direction, that would be wild.

**Comment by SmilyOrg** [comment]
> I wish the Readme explicitly stated that all photos without Exif are ignored, I have most of my library like that so photofield is almost useless.

Hmm, they shouldn't be. Of course dates might be weird and geolocation won't work and so on, but the photos should still show up. Could you say more about the photos or share a sample?

> Also I know this is out of project scope but Automatic Mobile Upload is the missing piece to make this shiny and competitive. If you push the limits in that direction, that would be wild.

I totally see that, but honestly I don't have a lot of patience for dealing with app dev and app stores.

It would be good to document existing solutions that integrate well in this space however. I'm partial to PhotoSync, it's not perfect, but it's very much a set and forget system.

**Comment by evrial** [comment]
I'll try to repeat from scratch tomorrow and report to you.

**Comment by evrial** [comment]
Ok turned out running the selfhosted docker app on rpi4 wasn't the best idea, photofield loves computation so now I run it standalone locally on AMD 5600X desktop and storing local data and serving files over smb, night and day! This app is class of its own, appreciate your work!

**Comment by evrial** [comment]
My small suggestion is rescan triggered automatically or asking for rescan only new files

**Comment by SmilyOrg** [comment]
> Ok turned out running the selfhosted docker app on rpi4 wasn't the best idea, photofield loves computation so now I run it standalone locally on AMD 5600X desktop and storing local data and serving files over smb, night and day! This app is class of its own, appreciate your work!

Thanks! Good to know that the rpi4 is not the best candidate. I'm running it on a DS418play, so that's probably acts as the minimum spec, but it's fairly good at using extra power that you throw at it :)

> My small suggestion is scan/rescan triggered automatically or asking for rescan only new files

Yeah that would be good, there is #73 for "watch" functionality, but that can get a little tricky (see #97). Maybe just adding scheduled rescans is a good compromise.

**Comment by evrial** [comment]
I mean automatic data rescan is much more desirable than automatic config reload.
Also fount a big problem, gallery is empty when at least one mp4 exists Unable to load image info meta image: unknown format path/to/file.mp4

**Comment by SmilyOrg** [comment]
> I mean automatic data rescan+view reload is much more desirable than automatic config reload. 

Yeah that makes sense.

> Also found a big problem, gallery is empty when at least one mp4 exists `Unable to load image info meta image: unknown format path/to/file.mp4`

Hmm... the metadata extraction shouldn't block other files or photos really. It could be a bug. To fix that error you can install/add `exiftool` to the PATH where photofield is running, which should make extraction work (see similar issue #98).

> Another problem - wall layout for some folders is empty.

Do other layouts work?

![image](https://github.com/SmilyOrg/photofield/assets/1451391/1c764a90-387d-4c4e-ab10-a0795d87f46e)

Does clicking that button fix it? (It shouldn't be necessary anymore, but 🤷‍♂️)

> And other layouts aren't much usable because they are grouped by date and looks ugly on wide monitor.

By "grouped by date" you mean that it creates too many new lines with only a few photos per line? Or that you'd expect a different order, for example alphabetical?

**Comment by evrial** [comment]
>Hmm... the metadata extraction shouldn't block other files or photos really. It could be a bug. To fix that error you can install/add exiftool to the PATH where photofield is running, which should make extraction work (see similar issue https://github.com/SmilyOrg/photofield/issues/98).
Thanks this worked

>Do other layouts work?
Only timeline and album, wall and map are empty and nothing helps

>By "grouped by date" you mean that it creates too many new lines with only a few photos per line? Or that you'd expect a different order, for example alphabetical?
Yea I wish they fill the screen, PiGallery2 actually is the best in this

**Comment by SmilyOrg** [comment]
> Only timeline and album, wall and map are empty and nothing helps

Weird, are there any errors in logs or in the browser console (F12)?

> Yea I wish they fill the screen, PiGallery2 actually is the best in this

Yeah this has also bothered me before, opened #104 to track it

**Comment by evrial** [comment]
> Weird, are there any errors in logs or in the browser console (F12)?
nothing
> Yeah this has also bothered me before, opened https://github.com/SmilyOrg/photofield/issues/104 to track it
Sometimes you wish grouping, but annoying when each day taken one photo. If you copy pigallery2 in this would be fantastic

**Comment by evrial** [comment]
I isolated the bug, if I copy mp4 file to perfect functioning wall album, after reindex wall layout is empty and nothing even deleting and full refresh/reindex
```
scene loading eve
list infos sqlite        1 ms
list infos               1 ms
layout wall width 3440 cols 22
layout wall image 155.454545 124.363636
layout                   0 ms
scene load eve           1 ms
photos 506, scene 3440 x 211
```

**Comment by evrial** [comment]
Found another bug with db vacuum:
```
.\photofield.exe -vacuum
photofield 0.15.0
config path configuration.yaml
geo using file:data/geo/geoBoundariesCGAZ_ADM2_s5_twkb_p3.gpkg?vfs=vfs1&mode=ro
cache database version 13, migrating if needed
ffmpeg found at C:\Program Files\ffmpeg\ffmpeg.exe
thumbs database version 1, migrating if needed
extensions .jpg, .jpeg, .png, .avif, .bmp, .pam, .ppm, .jxl, .exr, .cr2, .dng, .mp4
20 collections
panic: sqlite: step: SQL logic error: no such column:

goroutine 1 [running]:
main.main()
        /home/runner/work/photofield/photofield/main.go:1373 +0x183e
```

**Comment by SmilyOrg** [comment]
Thanks for the reports! I created two tickets to track these. Not sure what's going on though...
