### ISSUE TITLE
Solid color thumbnail when fully zoomed out on wall

### ISSUE THREAD

**Issue by alnmy** [SmilyOrg/photofield#107]
**Describe the bug**
When fully zoomed out on the wall, a solid colour appears for the majority of images. When even slightly zooming in, a proper thumbnail appears. For the amount of space that each grid takes up on the screen, I would expect to see a proper thumbnail like the rest of the images have.

**Expected behavior**
Images with higher detail thumbnails appear

**Screenshots**
![obfuscated](https://github.com/SmilyOrg/photofield/assets/67667676/bbab764e-9d33-403a-a2cc-4cca9b9dcd4e)

**Desktop (please complete the following information):**
 - OS: OpenSUSE MicroOS, Photofield running as prebuilt executable from Github and inside an Arch Linux distrobox environment 
 - Browser Brave
 - Version 0.15.0

**Additional context**
Slightly zooming in reveals higher detail thumbnails. Image censored, completely black grids are images with higher detail thumbnails and I couldn't bother doing the rest so I just blurred the other half of the image.

**Comment by alnmy** [comment]
I just realised that https://github.com/SmilyOrg/photofield/blob/main/defaults.yaml#L27 exists, though I guess a point could still be made about a default which could be made better but I'm closing this.

**Comment by SmilyOrg** [comment]
I also feel like the default is a little too aggressive, so if you find a better default, let me know and I'll try to change it when I can.
