### ISSUE TITLE
No photos found

### ISSUE THREAD

**Issue by kawaii2020** [SmilyOrg/photofield#111]
![image](https://github.com/user-attachments/assets/35b3590b-dd3b-46ec-afcc-7f557a865648)

There should be millions of photos in that folder. But none of them are indexed.

![image](https://github.com/user-attachments/assets/2bac5608-62cf-4b9b-8dd5-c9be704fdbfc)

![image](https://github.com/user-attachments/assets/d9de651e-7e62-4443-9c66-c8044888bf88)

![image](https://github.com/user-attachments/assets/e5091955-2a0a-4568-8a56-2f56a358e5f4)

**Comment by kawaii2020** [comment]
![image](https://github.com/user-attachments/assets/6818fcd9-ce37-49a4-8917-e02f990320ce)

**Comment by kawaii2020** [comment]
I have about 5 million photos, they are located in dozens of subfolders, is there a way to scan/index all of them at once?

**Comment by Rubyer77** [comment]
@pandayummy i have the same problem, it sees the subfolders but not the files. 

how did you fix this?

**Comment by SmilyOrg** [comment]
> @pandayummy i have the same problem, it sees the subfolders but not the files. 
> 
> how did you fix this?

Hi! Does anything happen if you Rescan from the collection menu? What are the extensions of your images?

**Comment by Rubyer77** [comment]
> > [@pandayummy](https://github.com/pandayummy) i have the same problem, it sees the subfolders but not the files.
> > how did you fix this?
> 
> Hi! Does anything happen if you Rescan from the collection menu? What are the extensions of your images?

it works when I click `rescan`. First time I see images displayed in `photofield` 👍

**Comment by Rubyer77** [comment]
jpeg

**Comment by SmilyOrg** [comment]
> > > [@pandayummy](https://github.com/pandayummy) i have the same problem, it sees the subfolders but not the files.
> > > how did you fix this?
> > 
> > Hi! Does anything happen if you Rescan from the collection menu? What are the extensions of your images?
> 
> it works when I click `rescan`. First time I see images displayed in `photofield` 👍 

Good to hear! The indexing story could be smoother for sure, see https://github.com/SmilyOrg/photofield/issues/81
