### ISSUE TITLE
No way to close the Hamburger Menu

### ISSUE THREAD

**Issue by Darthagnon** [SmilyOrg/photofield#18]
**Describe how to reproduce the bug**
Click on the top-left Hamburger Menu on PC, and there is no way to close the menu. Page must be reloaded. (Similar with settings icon, but at least that can be closed by clicking on it again).

**Expected behavior**
Clicking off the Hamburger Menu should close it. Likewise, clicking off the Settings icon should (maybe?) close the settings menu. What about combining the settings menu and the hamburger menu?

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Ungoogled Chromium 90
 - Version: Photofield 0.5.0

**Smartphone (please complete the following information):**
N/A

**Comment by SmilyOrg** [comment]
Hmm, does it not work if you click on the darkened region to the right of it? That works for me on Firefox/Edge.

I think clicking off settings to close it is a good idea, it's a little annoying to have to explicitly close it.

The idea behind the sidebar vs. settings is that sidebar is more "admin area / general navigation" and the settings gear is more like "display settings" for the current view. But I see how it's a little awkward to have both 🤔

**Comment by Darthagnon** [comment]
Will test in a few other browsers I have installed

**Comment by Darthagnon** [comment]
Gear menu (right) stays open in Ungoogled Chromium and Brave, but since the sidebar has been deprecated, this is a smaller issue. The new menu works fine, clicking off it dismisses it :)
