### ISSUE TITLE
After scrolling for a while, photos no longer load

### ISSUE THREAD

**Issue by Darthagnon** [SmilyOrg/photofield#19]
**Describe the bug**
After scrolling for a while in a large album, I reach pixellated thumbnails, then blurred thumbnails, then just a blur. The blur no longer responds to clicks or loads.

**To Reproduce**
1. Go to '[https://demo.photofield.dev/](https://demo.photofield.dev/)'
2. Enter a large album and scroll for a while
3. Pictures will eventually stop loading

**Expected behavior**
Memory to be cleared of earlier thumbnails and the new thumbnails to be loaded while scrolling, rather than stopping at some point.

**Screenshots**
*of course, once I try and get a screenshot, I couldn't replicate. Maybe click-zooming clears memory and gets things working again?*

**Desktop (please complete the following information):**
 - OS: Windows 10 v1709
 - Browse: Ungoogled Chromium
 - Version: 90

**Smartphone (please complete the following information):**
N/A

**Comment by SmilyOrg** [comment]
So this would happen if the server stops responding to any requests, so the browser can only do what it can with what it already has (preloaded lower quality images). For technical reasons clicks also depend on the server being there and ready, so I think you just ran into the server being overloaded at times :)

I would be interested if it happens for you locally though if you end up trying it out!

**Comment by Darthagnon** [comment]
I'll test more extensively locally! I was having great performance with my test folder full of desktop wallpapers!

**Comment by SmilyOrg** [comment]
Closing this as there seems to be nothing more to do :)
