### ISSUE TITLE
Left/Right keys don't proceed past photos with different aspect ratios

### ISSUE THREAD

**Issue by Darthagnon** [SmilyOrg/photofield#20]
**Describe the bug**
Testing on localhost, I found that I had some trouble cycling through photos with the arrow keys when the aspect ratio changed. [Here's the photos I was testing with](https://drive.google.com/drive/folders/1-8oFoCHcDJH4KKx8tfx78HoJgy2YiJsu?usp=sharing); I would start at the beginning, press `Right` `Right` `Right` [...] and then I couldn't cycle from the 2nd to last (black and white cartoon) on to the last photo (stars over beach). Cycling left, I had no problems, despite identical changes in aspect ratio.

**Expected behavior**
Should be able to cycle with arrow keys without it randomly stopping? Unknown cause, see above for the sample photos.

**Desktop (please complete the following information):**
 - OS: Win10 v1709
 - Browser: Ungoogled Chromium
 - Version: 90

**Smartphone (please complete the following information):**
N/A

**Comment by Darthagnon** [comment]
## Suggestion:

Up/Down arrow keys seem to do nothing at the moment - would it be possible to set them to zoom in/out? or navigation...

**Comment by SmilyOrg** [comment]
I can reproduce it easily with your files and it definitely looks all kinds of buggy! It might have something to do with the recent refactoring in #17. I'll look into it, thanks!

> Up/Down arrow keys seem to do nothing at the moment - would it be possible to set them to zoom in/out? or navigation...

Hmm, not sure how useful it is for them to zoom in/out (how often do you want to zoom into the e.g. center specifically?), but maybe some kind of extra navigation makes sense? Like skipping to the next day or next event or something like that 🤔

**Comment by SmilyOrg** [comment]
@Darthagnon hey, this should be now fixed in v0.5.1 that will be published [soon](https://github.com/SmilyOrg/photofield/runs/8215536978?check_suite_focus=true). Let me know if you still see this problem.

**Comment by Darthagnon** [comment]
Fixed! Thank you so much!

RE: the "zoom" idea, it was more along the lines of, say, down arrow also doing what ESC currently does, and up arrow doing what ENTER (or spacebar preview) does in other software; might be a bit too weird, though.

**Comment by Darthagnon** [comment]
Is the loading/indexing animation new? I love it!

**Comment by SmilyOrg** [comment]
> Fixed! Thank you so much!

Thanks for reporting!

> RE: the "zoom" idea, it was more along the lines of, say, down arrow also doing what ESC currently does, and up arrow doing what ENTER (or spacebar preview) does in other software; might be a bit too weird, though.

Hmm yeah, I'll have to try it out. Not sure what up arrow would do since it's already in "preview" while zoomed in, no?

> Is the loading/indexing animation new? I love it!

It's been in there for a version or two, but you might not see it if it loads quickly enough :)
