### ISSUE TITLE
Found some images that Photofield doesn't like

### ISSUE THREAD

**Issue by Darthagnon** [SmilyOrg/photofield#44]
**Describe the bug**
The attached (ZIP) images display as big red squares in Photofield v0.7.0

**To Reproduce**
Load up photofield and get it to process these photos (JPG, PNG, wallpapers from Telegram, sourced from [here](https://blog.1a23.com/2020/02/13/telegram-chat-backgrounds-patterns-extracted/))
[Telegram wallpapers.zip](https://github.com/SmilyOrg/photofield/files/10189767/Telegram.wallpapers.zip). At least on Windows, running v0.7.0 plain (no exiftool or anything) they display as big red squares.

**Expected behavior**

**Screenshots**
![brave_bHDPbCcung](https://user-images.githubusercontent.com/20792748/206577135-cf0eb7de-219a-4bdc-902c-4c4ad4f7c2ce.png)

**Desktop (please complete the following information):**
 - OS: Win10 v1709
 - Browser: Ungoogled Chromium, Brave
 - Version: v90, v1.45.116

**Comment by Darthagnon** [comment]
I also noticed it doesn't seem to pay attention to nested folders? Didn't notice that before... e.g. I have the above wallpapers organised as:
`/Wallpapers/iPhone Wallpapers/Telegram wallpapers/wall.jpg` (where `/` is Photofield's root)

### Expected display:
Album layout:
- Grouping wallpapers by subfolder, i.e. "Album"
Timeline layout:
- Grouping using month/day/time/year, more or less as current "Default"/"Album" layout
- But with `<h2>` = Year/Month, `<h3>` = Day/Date, order invisibly by Time?
Wall layout:
- exactly as-is, a flat display of all images, ordered (invisibly) I assume by date and subfolder?
Default layout:
- no idea, deprecate as uninformative and replaced by other layouts? Photofield doesn't (yet) save different layouts per folder as far as I can tell, nor are there enough different layouts to warrant this (maybe if Geo and People tags are implemented, it would be useful)

### How it's actually displayed
Album layout:
- `<h2>` is Day, Month [numerical date], `<h3>` is Time
- ... Doesn't seem to sort by any definition of "Album"...? Confuzzled.
Timeline layout:
- Full date, time, year grouping... not very useful, more or less a zoomed-out duplicate version of current "Album"
Wall layout:
- It's perfect!
Default:
- ??? Seems to duplicate "Album", and doesn't mean "Default for this folder" (which isn't saved or currently worth saving)

**Comment by Darthagnon** [comment]
Needless to say, but the images seem to open fine in everything else I've tried.

**Comment by SmilyOrg** [comment]
Hey, thanks for reporting! I'll take a look when I get the chance 😊
